---
driver:
  name: vagrant
  
provisioner:
  name: chef_solo

transport:
  name: winrm
  elevated: true

platforms:
  - name: windows-2012r2
    driver_config:
      box: mwrock/Windows2012R2
      customize:
        memory: 2048

suites:
  - name: default
    os_type: windows
    shell_type: powershell
    driver:
      winrm_transport: :plaintext
      network:
        - ["private_network", {ip: "192.168.50.11"}]
    run_list:
      - recipe[nuget_dsc::default]
    attributes:
