---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: windows-2012r2
    driver:
      box: VzISD/Windows2012R2
      customize:
        memory: 2048

suites:
  - name: server
    driver:
      network:
        - ["private_network", {ip: "192.168.50.11"}]
    run_list:
      - recipe[serverBase::labSettings]
      - recipe[serverBase::wmf5]
      - recipe[serverBase::lcm]
      - recipe[serverBase::webLoader]
      - recipe[serverBase::labNetworking]
      - recipe[nuget]
      - recipe[nuget::nuget_client]
    attributes:
